### ISSUE TITLE
Plugin Manager Update Checker Fails

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/RoyalCommands#1]
Best bet would be overhauling this system to instead use SpigotMC's Resources section.

Currently this method uses a .rss file that no longer exists on BukkitDev.

https://github.com/WMCAlliance/RoyalCommands/blob/master/modules/RoyalCommands/src/main/java/org/royaldev/royalcommands/rcommands/CmdPluginManager.java#L237

**Comment by Mu5tank05** [comment]
It may be easier to ping back to here

**Comment by WizardCM** [comment]
We don't hold a database of every plugin out there, including their latest versions, unless you'd like to maintain it. ;)

**Comment by BlaneyXYZ** [comment]
https://github.com/SpigotMC/XenforoResourceManagerAPI

**Comment by BlaneyXYZ** [comment]
Closed in [20993c6](https://github.com/WMCAlliance/RoyalCommands/commit/20993c606fc36645f24cb531c002706df115db99)
